# Generated by Django 3.2 on 2022-04-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headline',
        ),
    ]
