# Generated by Django 3.2 on 2022-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="What's up? Travel and Lifestyle blog", max_length=255),
        ),
    ]
