# Generated by Django 3.2 on 2022-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0002_remove_post_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='placeholder1', upload_to='images/'),
        ),
    ]
