# Generated by Django 3.2 on 2022-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0004_remove_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='placeholder1', upload_to='images/'),
        ),
    ]
