# Generated by Django 3.2 on 2022-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0004_auto_20220223_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Life Style', max_length=255),
        ),
    ]
