# Generated by Django 3.2 on 2022-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images/profile/'),
        ),
    ]
