# Generated by Django 3.2 on 2022-02-23 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellifestyleblog22', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='blog_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
