# Generated by Django 3.2 on 2022-02-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0008_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
