# Generated by Django 3.2.13 on 2022-04-28 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0010_auto_20220428_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
