# Generated by Django 3.2 on 2022-05-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0012_alter_post_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
