# Generated by Django 3.2 on 2022-02-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0018_alter_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
