# Generated by Django 3.2 on 2022-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0022_rename_image_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='images/'),
        ),
    ]
