# Generated by Django 3.2 on 2022-02-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0023_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images/profile/'),
        ),
    ]
