# Generated by Django 3.2 on 2022-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0026_auto_20220224_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.TextField(default=''),
        ),
    ]
