# Generated by Django 3.2 on 2022-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0031_auto_20220306_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_addded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
