# Generated by Django 3.2 on 2022-03-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0033_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headline',
        ),
    ]
