# Generated by Django 3.2 on 2022-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0036_auto_20220312_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.TextField(blank=True, default='nope', null=True),
        ),
    ]
