# Generated by Django 3.2 on 2022-03-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellifestyleblog22', '0040_auto_20220312_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_addded']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='date_addded',
        ),
    ]
